jobs:
  crowdin-push:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      env:
        CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
        CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      name: Push sources to Crowdin
      uses: crowdin/github-action@cb33a030bb1675169b76617d5805242aeea6eaec
      with:
        config: crowdin.yml
        crowdin_branch_name: master
        download_translations: false
        upload_sources: true
        upload_translations: false
name: Crowdin Push
on:
  repository_dispatch:
    types: trigger-ga___crowdin-push.yml
