jobs:
  crowdin-pull:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      env:
        CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
        CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      name: Pull Crowdin translations
      uses: crowdin/github-action@cb33a030bb1675169b76617d5805242aeea6eaec
      with:
        commit_message: New Crowdin translations
        config: crowdin.yml
        create_pull_request: true
        crowdin_branch_name: master
        download_translations: true
        github_user_email: <>
        github_user_name: github-actions
        localization_branch_name: localization
        pull_request_base_branch_name: master
        pull_request_body: New Crowdin translations
        pull_request_title: New Crowdin translations
        upload_sources: false
        upload_translations: false
name: Crowdin Pull
on:
  repository_dispatch:
    types: trigger-ga___crowdin-pull.yml
