jobs:
  stale:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/stale@v9
      with:
        days-before-close: 3
        days-before-stale: 14
        exempt-issue-labels: official, on hold
        exempt-pr-labels: official, on hold
        stale-issue-label: stale
        stale-issue-message: 'This issue has been automatically marked as stale because
          it has not had recent activity. It will be closed if no further activity
          occurs.  Thank you for your contributions.


          Do not remove this label manually, it should be removed by the bot when
          new activity occurs.

          '
        stale-pr-label: stale
        stale-pr-message: 'This PR has been automatically marked as stale because
          it has not had recent activity. It will be closed if no further activity
          occurs.  Thank you for your contributions.


          Do not remove this label manually, it should be removed by the bot when
          new activity occurs.

          '
name: Handle stale issues and PRs
on:
  repository_dispatch:
    types: trigger-ga___stale.yml
permissions:
  issues: write
  pull-requests: write
