jobs:
  action:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: dessant/support-requests@47d5ea12f6c9e4a081637de9626b7319b415a3bf
      with:
        close-issue: true
        github-token: ${{ github.token }}
        issue-comment: ':wave: @{issue-author}, we use GitHub issue tracker exclusively
          for bug reports. However, this issue appears to be a support or a feature
          request. Please use our [Forums on the website](https://mcreator.net/forum)
          for support and feature requests.

          '
        issue-lock-reason: off-topic
        lock-issue: true
        support-label: 'invalid: support request'
name: Support Requests
on:
  repository_dispatch:
    types: trigger-ga___support.yml
permissions:
  issues: write
